# Generated by Django 5.0.4 on 2024-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tbl', '0002_auto_20240904_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='Student',
            name='ability',
            field=models.IntegerField(default=3),
        )
    ]
