# Generated by Django 5.0.4 on 2024-09-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tbl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Student',
            name='graduated',
            field=models.BooleanField(default = False),
            preserve_default=False,
        )
    ]
